
try [[
  print("Hello world!")
  error("error!")
catch err
  print(err)
--  error(err)
finally
  print("Finally!")
]]
